/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.38
 * Generated at: 2020-11-23 03:36:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.dealight.store;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.dealight.domain.UserVO;

public final class nstore_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1605067212452L));
    _jspx_dependants.put("jar:file:/Users/hyeonjung/Documents/Coding/spring/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/dealight_project/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/dealight/store/../../includes/mainMenu.jsp", Long.valueOf(1606099596000L));
    _jspx_dependants.put("jar:file:/Users/hyeonjung/Documents/Coding/spring/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/dealight_project/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.dealight.domain.UserVO");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- 현수현수현수 -->\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("<script src=\"https://use.fontawesome.com/releases/v5.2.0/js/all.js\"></script>\n");
      out.write("\n");
      out.write("<!-- Add icon library -->\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("\thref=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\n");
      out.write("\n");

	UserVO user = (UserVO) session.getAttribute("user");
String loginState = "";
String display = ""; //로그인 전에 로그아웃 메뉴 숨기기
//세션에 로그인 정보가 담겼다면 로그인 모달창 비활성화
if (user != null) {
	loginState = "onclick=\"goMypage()\"";
} else {
	loginState = "onclick=\"openModal()\"";
	display = "none";
}

      out.write("\n");
      out.write("\n");
      out.write("<style>\n");
      out.write("* {\n");
      out.write("\tbox-sizing: border-box;\n");
      out.write("}\n");
      out.write("\n");
      out.write("body {\n");
      out.write("\tmargin: 0;\n");
      out.write("\tpadding: 0;\n");
      out.write("\tborder: 0;\n");
      out.write("\tfont-family: Arial, Helvetica, sans-serif;\n");
      out.write("}\n");
      out.write("/* .topDiv {\n");
      out.write("   border: 1px solid black;\n");
      out.write("   width: 100%;\n");
      out.write("   height: 100px;\n");
      out.write("   display: flex;\n");
      out.write("   /* 자식에 영향 주기 위한 설정 */\n");
      out.write("/* 자식인 inline-block들을 가운데정렬\n");
      out.write("            justify-content: center; */\n");
      out.write("}\n");
      out.write("* /\n");
      out.write(".top {\n");
      out.write("\toverflow: hidden;\n");
      out.write("\tflex: 1;\n");
      out.write("\t/* 비율을 1:1:1로 주기 */\n");
      out.write("\theight: 35px;\n");
      out.write("\tdisplay: inline-block;\n");
      out.write("\tz-index: 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".dropbtn {\n");
      out.write("\tmargin-top: 0;\n");
      out.write("\tpadding-left: 10px;\n");
      out.write("\tborder: none;\n");
      out.write("\toutline: none;\n");
      out.write("\tfont-size: 30px;\n");
      out.write("\tcursor: pointer;\n");
      out.write("\tdisplay: inline-block;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".dropdown {\n");
      out.write("\tposition: absolute;\n");
      out.write("\tdisplay: inline-block;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".dropdown-content {\n");
      out.write("\tdisplay: none;\n");
      out.write("\tposition: absolute;\n");
      out.write("\tmin-width: 160px;\n");
      out.write("\tz-index: 1;\n");
      out.write("\tbackground-color: #f1f1f1;\n");
      out.write("\tbox-shadow: 0px 8px 16px 0px rgba(0, 0, 0, 0.2);\n");
      out.write("}\n");
      out.write("\n");
      out.write(".dropdown-content a {\n");
      out.write("\tdisplay: block;\n");
      out.write("\tpadding: 3px;\n");
      out.write("\tcolor: black;\n");
      out.write("\tfont-size: 15px;\n");
      out.write("\ttext-decoration: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".dropdown-content a:hover {\n");
      out.write("\tbackground-color: crimson;\n");
      out.write("\tcolor: white;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".dropbtn:hover .dropdown-content {\n");
      out.write("\tdisplay: block;\n");
      out.write("\tz-index: 99;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".logo {\n");
      out.write("\tmargin-left: 40%;\n");
      out.write("\tpadding: 3px 8px;\n");
      out.write("\tdisplay: inline-block;\n");
      out.write("\theight: 100%;\n");
      out.write("\ttext-align: center;\n");
      out.write("\tfont-size: 30px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".logo-content {\n");
      out.write("\tfloat: left;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".rightIcon {\n");
      out.write("\tfloat: right;\n");
      out.write("\tpadding: 3px 8px;\n");
      out.write("\tfont-size: 28px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".mydropbtn {\n");
      out.write("\tcolor: white;\n");
      out.write("\tz-index: 1;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".mydropdown {\n");
      out.write("\tposition: relative;\n");
      out.write("\tdisplay: inline-block;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".mydropdown-content {\n");
      out.write("\tdisplay: none;\n");
      out.write("\tposition: absolute;\n");
      out.write("\tbackground-color: #f1f1f1;\n");
      out.write("\tmin-width: 160px;\n");
      out.write("\tbox-shadow: 0px 8px 16px 0px rgba(0, 0, 0, 0.2);\n");
      out.write("\tz-index: 1;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".mydropdown-content a {\n");
      out.write("\tcolor: black;\n");
      out.write("\tfont-size: 15px;\n");
      out.write("\tpadding: 3px 5px;\n");
      out.write("\ttext-decoration: none;\n");
      out.write("\tdisplay: block;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".mydropdown-content a:hover {\n");
      out.write("\tbackground-color: #ddd;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".mydropdown:hover .mydropdown-content {\n");
      out.write("\tdisplay: block;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".middleDiv {\n");
      out.write("\twidth: 100%;\n");
      out.write("\theight: 600px;\n");
      out.write("\tposition: relative;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".imgContainer {\n");
      out.write("\twidth: 100%;\n");
      out.write("\theight: 100%;\n");
      out.write("\tposition: absolute;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".imgContainer img {\n");
      out.write("\tposition: absolute;\n");
      out.write("\ttop: 0;\n");
      out.write("\tleft: 0;\n");
      out.write("\twidth: 100%;\n");
      out.write("\theight: 100%;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".searchBarDiv {\n");
      out.write("\tborder: 1px solid black;\n");
      out.write("\tmargin: 0 auto;\n");
      out.write("\tmargin-top: 100px;\n");
      out.write("\twidth: 40%;\n");
      out.write("\theight: 100px;\n");
      out.write("\tposition: relative;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".topRow {\n");
      out.write("\tborder: 1px solid black;\n");
      out.write("\tdisplay: inline-block;\n");
      out.write("\twidth: 100%;\n");
      out.write("\theight: 50%;\n");
      out.write("\tbackground-color: white;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".topRowBar {\n");
      out.write("\tborder: 1px solid black;\n");
      out.write("\tfloat: left;\n");
      out.write("\twidth: 33.33%;\n");
      out.write("\theight: 100%;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".bottomRow {\n");
      out.write("\tborder: 1px solid black;\n");
      out.write("\tdisplay: block;\n");
      out.write("\tposition: absolute;\n");
      out.write("\ttop: 50%;\n");
      out.write("\twidth: 100%;\n");
      out.write("\theight: 50%;\n");
      out.write("\tbackground-color: white;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".bottomRowBar {\n");
      out.write("\tborder: 1px solid black;\n");
      out.write("\tfloat: left;\n");
      out.write("\twidth: 80%;\n");
      out.write("\theight: 100%;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".searchbtn {\n");
      out.write("\tbackground-color: crimson;\n");
      out.write("\tcolor: white;\n");
      out.write("\twidth: 20%;\n");
      out.write("\theight: 100%;\n");
      out.write("\tborder: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".dealTitleDiv {\n");
      out.write("\tborder: 1px solid rgb(151, 151, 151);\n");
      out.write("\twidth: 80%;\n");
      out.write("\theight: 50px;\n");
      out.write("\tmargin: 30px auto 0 auto;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".dealTitle {\n");
      out.write("\tborder: 1px solid black;\n");
      out.write("\twidth: 150px;\n");
      out.write("\theight: 100%;\n");
      out.write("\tdisplay: inline-block;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".dealDiv {\n");
      out.write("\tborder: 1px solid black;\n");
      out.write("\twidth: 80%;\n");
      out.write("\theight: 1200px;\n");
      out.write("\tmargin: auto;\n");
      out.write("\toverflow: hidden;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".dealContainer {\n");
      out.write("\tborder: 1px solid black;\n");
      out.write("\tdisplay: inline-block;\n");
      out.write("\tmargin: 23px 30px;\n");
      out.write("\twidth: 28%;\n");
      out.write("\theight: 350px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".dealImg {\n");
      out.write("\tborder: 1px solid black;\n");
      out.write("\tdisplay: block;\n");
      out.write("\twidth: 100%;\n");
      out.write("\theight: 70%;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".dealText {\n");
      out.write("\tborder: 1px solid black;\n");
      out.write("\tdisplay: block;\n");
      out.write("\twidth: 100%;\n");
      out.write("\theight: 30%;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".footer {\n");
      out.write("\tborder: 1px solid black;\n");
      out.write("\twidth: 100%;\n");
      out.write("\theight: 180px; . mydropbtn { color : white;\n");
      out.write("\tz-index: 1;\n");
      out.write("\tcursor: pointer;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\t<!-- <div class=\"top-container\"> -->\n");
      out.write("\t\t<div class=\"topDiv\" id=\"topDiv\">\n");
      out.write("\t\t\t<div class=\"top\" style=\"height: 35px\"> <!-- 임시로 높이 지정해둠 -->\n");
      out.write("\t\t\t\t<div class=\"dropdown\">\n");
      out.write("\t\t\t\t\t<button class=\"dropbtn\">\n");
      out.write("\t\t\t\t\t\t<i class=\"fas fa-bars\" color=\"black\"></i>\n");
      out.write("\t\t\t\t\t\t<div class=\"dropdown-content\">\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\">핫딜 찾기</a> <a href=\"#\">매장 찾기</a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</button>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<!--end dropdown-->\n");
      out.write("\n");
      out.write("\t\t\t\t<div class=\"logo\">\n");
      out.write("\t\t\t\t\t<div class=\"logo-content\">\n");
      out.write("\t\t\t\t\t\t<a href=\"/dealight/dealight\" style=\"text-decoration: none\"> <i\n");
      out.write("\t\t\t\t\t\t\tclass=\"fas fa-circle\" color=\"red\" style=\"font-size: 20px\"></i> <i\n");
      out.write("\t\t\t\t\t\t\tclass=\"fas fa-circle\" color=\"yellow\" style=\"font-size: 20px\"></i>\n");
      out.write("\t\t\t\t\t\t\t<i class=\"fas fa-circle\" color=\"green\" style=\"font-size: 20px\"></i>\n");
      out.write("\t\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"logo-content\">\n");
      out.write("\t\t\t\t\t\t<a href=\"/dealight/dealight\" class=\"dealight\" color=\"black\"\n");
      out.write("\t\t\t\t\t\t\tstyle=\"text-decoration: none\">Dealight</a>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<!--end logo-->\n");
      out.write("\t\t\t\t<!--이 icon들은 굳이 div로 안 나눠도 될듯?-->\n");
      out.write("\t\t\t\t<div class=\"rightIcon\">\n");
      out.write("\t\t\t\t\t<a href=\"#\"><i class=\"fas fa-question-circle\" color=\"black\"></i></a>\n");
      out.write("\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"rightIcon\">\n");
      out.write("\t\t\t\t\t<a href=\"#\"><i class=\"fas fa-bell\" color=\"black\"></i></a>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t<div class=\"rightIcon\">\n");
      out.write("\t\t\t\t\t<div class=\"mydropdown\">\n");
      out.write("\t\t\t\t\t\t");
      out.write("\n");
      out.write("\t\t\t\t\t\t<a class=\"mydropbtn\" id=\"openModal\"");
      out.print(loginState);
      out.write("\"><i\n");
      out.write("\t\t\t\t\t\t\tclass=\"fas fa-user\" color=\"black\"></i></a>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<div class=\"mydropdown-content\">\n");
      out.write("\t\t\t\t\t\t\t<a href=\"/dealight/mypage/reservation\">예약내역(미구현)</a> <a\n");
      out.write("\t\t\t\t\t\t\t\thref=\"#waiting/list\">웨이팅(미구현)</a>\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"/dealight/mypage/review/writable-list\">나의리뷰</a>\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#like\">좋아요(미구현)</a> <a href=\"/dealight/mypage/modify\">회원정보수정</a>\n");
      out.write("\t\t\t\t\t\t\t<a href=\"/dealight/logout\" style=\"display:");
      out.print(display );
      out.write("\">로그아웃</a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t<!-- </div> -->\n");
      out.write("\t<script>\n");
      out.write("\n");
      out.write(" //1. 버튼을 누르면 모달창이 띄어지고, 배경 회색으로 변경\n");
      out.write("   function openModal(){\n");
      out.write("       document.getElementById('content').style.display='block';\n");
      out.write("       document.body.style.backgroundColor = \"rgba(0,0,0,0.4)\";\n");
      out.write("\n");
      out.write("}\n");
      out.write("\n");
      out.write("//2. X버튼을 누르면 모달창이 사라지고 원상복귀\n");
      out.write("   function closebtn(){\n");
      out.write("   document.getElementById('content').style.display='none';\n");
      out.write("   document.body.style.backgroundColor = \"white\";\n");
      out.write("}\n");
      out.write("\n");
      out.write("//3. login상태에서 사람모양 클릭시 mypage(예약내역)로 이동\n");
      out.write("function goMypage(){\n");
      out.write("\t location.href=\"/dealight/mypage/reservation\";\n");
      out.write("\n");
      out.write("}\n");
      out.write("   </script>");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<!-- 다울 -->\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/store.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\t<div class=\"container\">\n");
      out.write("\t\n");
      out.write("\t\t<div class=\"left\">\n");
      out.write("\t\t\t<div class=\"column\">\n");
      out.write("\t\t\t\t<h1 >");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${store.storeNm }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h1>\n");
      out.write("\t\t\t\t<button type=\"button\">하트</button>\n");
      out.write("\t\t\t\t<br>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"column\">\n");
      out.write("\t\t\t\t<h1>매장정보</h1>\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"column\">\n");
      out.write("\t\t\t\t<h1>평점</h1>\n");
      out.write("\t\t\t\t<label>좋아요수:");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${store.eval.likeTotNum }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" </label>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t</div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/dealight/store/nstore.jsp(27,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${store.telno!= null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("\t\t\t\t\t<p>전화번호 : ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${store.telno }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</p>\n");
          out.write("\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/dealight/store/nstore.jsp(30,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${store.nstore.bizTm!= null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("\t\t\t\t\t<p>영업시간 : ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${store.nstore.bizTm }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</p>\n");
          out.write("\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /WEB-INF/views/dealight/store/nstore.jsp(33,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${store.nstore.menu!= null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("\t\t\t\t\t<p>메뉴 : ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${store.nstore.menu }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</p>\n");
          out.write("\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }
}
